services:
  r2flow:
    container_name: r2flow
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    tty: true
    stdin_open: true
    network_mode: "host"
    ports:
      - "6006:6006"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - KITTI360_ROOT=${KITTI360_ROOT:-/tmp/dummy_dataset}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - .:/home/docker/workspace
      - ${KITTI360_ROOT:-/tmp/dummy_dataset}:/home/docker/workspace/r2flow/data/kitti_360/dataset
    shm_size: 16g
    entrypoint: ["bash"]
